import re

class processor:
    example = "¿Cuantos dólares son 2 euros?"
    keywords = ["cuantos"]

    currency_list = {
        "AED": "United Arab Emirates Dirham",
        "AFN": "Afghan Afghani",
        "ALL": "Albanian Lek",
        "AMD": "Armenian Dram",
        "ANG": "Netherlands Antillean Guilder",
        "AOA": "Angolan Kwanza",
        "ARS": "Argentine Peso",
        "AUD": "Australian Dollar",
        "AWG": "Aruban Florin",
        "AZN": "Azerbaijani Manat",
        "BAM": "Bosnia-Herzegovina Convertible Mark",
        "BBD": "Barbadian Dollar",
        "BDT": "Bangladeshi Taka",
        "BGN": "Bulgarian Lev",
        "BHD": "Bahraini Dinar",
        "BIF": "Burundian Franc",
        "BMD": "Bermudan Dollar",
        "BND": "Brunei Dollar",
        "BOB": "Bolivian Boliviano",
        "BRL": "Brazilian Real",
        "BSD": "Bahamian Dollar",
        "BTC": "Bitcoin",
        "BTN": "Bhutanese Ngultrum",
        "BWP": "Botswanan Pula",
        "BYR": "Belarusian Ruble",
        "BZD": "Belize Dollar",
        "CAD": "Canadian Dollar",
        "CDF": "Congolese Franc",
        "CHF": "Swiss Franc",
        "CLF": "Chilean Unit of Account",
        "CLP": "Chilean Peso",
        "CNH": "CNH",
        "CNY": "Chinese Yuan",
        "COP": "Colombian Peso",
        "CRC": "Costa Rican Colón",
        "CUP": "Cuban Peso",
        "CVE": "Cape Verdean Escudo",
        "CZK": "Czech Republic Koruna",
        "DEM": "German Mark",
        "DJF": "Djiboutian Franc",
        "DKK": "Danish Krone",
        "DOP": "Dominican Peso",
        "DZD": "Algerian Dinar",
        "EGP": "Egyptian Pound (EGP)",
        "ERN": "Eritrean Nakfa (ERN)",
        "ETB": "Ethiopian Birr (ETB)",
        "EUR": "Euro (€)",
        "FIM": "Finnish Markka (FIM)",
        "FJD": "Fijian Dollar (FJD)",
        "FKP": "Falkland Islands Pound (FKP)",
        "FRF": "French Franc (FRF)",
        "GBP": "British Pound (£)",
        "GEL": "Georgian Lari (GEL)",
        "GHS": "Ghanaian Cedi (GHS)",
        "GIP": "Gibraltar Pound (GIP)",
        "GMD": "Gambian Dalasi (GMD)",
        "GNF": "Guinean Franc (GNF)",
        "GTQ": "Guatemalan Quetzal (GTQ)",
        "GYD": "Guyanaese Dollar (GYD)",
        "HKD": "Hong Kong Dollar (HK$)",
        "HNL": "Honduran Lempira (HNL)",
        "HRK": "Croatian Kuna (HRK)",
        "HTG": "Haitian Gourde (HTG)",
        "HUF": "Hungarian Forint (HUF)",
        "IDR": "Indonesian Rupiah (IDR)",
        "IEP": "Irish Pound (IEP)",
        "ILS": "Israeli New Sheqel (₪)",
        "INR": "Indian Rupee (Rs.)",
        "IQD": "Iraqi Dinar (IQD)",
        "IRR": "Iranian Rial (IRR)",
        "ISK": "Icelandic Króna (ISK)",
        "ITL": "Italian Lira (ITL)",
        "JMD": "Jamaican Dollar (JMD)",
        "JOD": "Jordanian Dinar (JOD)",
        "JPY": "Japanese Yen (¥)",
        "KES": "Kenyan Shilling (KES)",
        "KGS": "Kyrgystani Som (KGS)",
        "KHR": "Cambodian Riel (KHR)",
        "KMF": "Comorian Franc (KMF)",
        "KPW": "North Korean Won (KPW)",
        "KRW": "South Korean Won (₩)",
        "KWD": "Kuwaiti Dinar (KWD)",
        "KYD": "Cayman Islands Dollar (KYD)",
        "KZT": "Kazakhstani Tenge (KZT)",
        "LAK": "Laotian Kip (LAK)",
        "LBP": "Lebanese Pound (LBP)",
        "LKR": "Sri Lankan Rupee (LKR)",
        "LRD": "Liberian Dollar (LRD)",
        "LSL": "Lesotho Loti (LSL)",
        "LTL": "Lithuanian Litas (LTL)",
        "LVL": "Latvian Lats (LVL)",
        "LYD": "Libyan Dinar (LYD)",
        "MAD": "Moroccan Dirham (MAD)",
        "MDL": "Moldovan Leu (MDL)",
        "MGA": "Malagasy Ariary (MGA)",
        "MKD": "Macedonian Denar (MKD)",
        "MMK": "Myanmar Kyat (MMK)",
        "MNT": "Mongolian Tugrik (MNT)",
        "MOP": "Macanese Pataca (MOP)",
        "MRO": "Mauritanian Ouguiya (MRO)",
        "MUR": "Mauritian Rupee (MUR)",
        "MVR": "Maldivian Rufiyaa (MVR)",
        "MWK": "Malawian Kwacha (MWK)",
        "MXN": "Mexican Peso (MX$)",
        "MYR": "Malaysian Ringgit (MYR)",
        "MZN": "Mozambican Metical (MZN)",
        "NAD": "Namibian Dollar (NAD)",
        "NGN": "Nigerian Naira (NGN)",
        "NIO": "Nicaraguan Córdoba (NIO)",
        "NOK": "Norwegian Krone (NOK)",
        "NPR": "Nepalese Rupee (NPR)",
        "NZD": "New Zealand Dollar (NZ$)",
        "OMR": "Omani Rial (OMR)",
        "PAB": "Panamanian Balboa (PAB)",
        "PEN": "Peruvian Nuevo Sol (PEN)",
        "PGK": "Papua New Guinean Kina (PGK)",
        "PHP": "Philippine Peso (Php)",
        "PKG": "PKG (PKG)",
        "PKR": "Pakistani Rupee (PKR)",
        "PLN": "Polish Zloty (PLN)",
        "PYG": "Paraguayan Guarani (PYG)",
        "QAR": "Qatari Rial (QAR)",
        "RON": "Romanian Leu (RON)",
        "RSD": "Serbian Dinar (RSD)",
        "RUB": "Russian Ruble (RUB)",
        "RWF": "Rwandan Franc (RWF)",
        "SAR": "Saudi Riyal (SAR)",
        "SBD": "Solomon Islands Dollar (SBD)",
        "SCR": "Seychellois Rupee (SCR)",
        "SDG": "Sudanese Pound (SDG)",
        "SEK": "Swedish Krona (SEK)",
        "SGD": "Singapore Dollar (SGD)",
        "SHP": "St. Helena Pound (SHP)",
        "SKK": "Slovak Koruna (SKK)",
        "SLL": "Sierra Leonean Leone (SLL)",
        "SOS": "Somali Shilling (SOS)",
        "SRD": "Surinamese Dollar (SRD)",
        "STD": "São Tomé &amp; Príncipe Dobra (STD)",
        "SVC": "Salvadoran Colón (SVC)",
        "SYP": "Syrian Pound (SYP)",
        "SZL": "Swazi Lilangeni (SZL)",
        "THB": "Thai Baht (THB)",
        "TJS": "Tajikistani Somoni (TJS)",
        "TMT": "Turkmenistani Manat (TMT)",
        "TND": "Tunisian Dinar (TND)",
        "TOP": "Tongan Paʻanga (TOP)",
        "TRY": "Turkish Lira (TRY)",
        "TTD": "Trinidad & Tobago Dollar (TTD)",
        "TWD": "New Taiwan Dollar (NT$)",
        "TZS": "Tanzanian Shilling (TZS)",
        "UAH": "Ukrainian Hryvnia (UAH)",
        "UGX": "Ugandan Shilling (UGX)",
        "USD": "US Dollar ($)",
        "UYU": "Uruguayan Peso (UYU)",
        "UZS": "Uzbekistani Som (UZS)",
        "VEF": "Venezuelan Bolívar (VEF)",
        "VND": "Vietnamese Dong (₫)",
        "VUV": "Vanuatu Vatu (VUV)",
        "WST": "Samoan Tala (WST)",
        "XAF": "Central African CFA Franc (FCFA)",
        "XCD": "East Caribbean Dollar (EC$)",
        "XDR": "Special Drawing Rights (XDR)",
        "XOF": "West African CFA Franc (CFA)",
        "XPF": "CFP Franc (CFPF)",
        "YER": "Yemeni Rial (YER)",
        "ZAR": "South African Rand (ZAR)",
        "ZMK": "Zambian Kwacha (1968–2012) (ZMK)",
        "ZMW": "Zambian Kwacha (ZMW)",
        "ZWL": "Zimbabwean Dollar (2009) (ZWL)",
    }

    @staticmethod
    def check_string(string, context):
        pideweather = re.search(r"\W*cuantos\s+(?P<from>.+?)\s+son\s+(?P<value>.+?)\s+(?P<to>.+?)", string, re.IGNORECASE)
        if pideweather:
            return {"actuator": "currency_converter", "parameters": {}, "confidence": 0.4, "context": {}}
